# Generated by Django 2.1.2 on 2018-10-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='name')),
                ('product_image', models.ImageField(default='images/No-image.jpg', upload_to='', verbose_name='foto')),
                ('product_info', models.TextField(verbose_name='info')),
                ('product_price', models.PositiveIntegerField(verbose_name='price')),
                ('product_status', models.IntegerField(choices=[(0, 'Deleted'), (1, 'To moderation'), (2, 'Active')], default=1, verbose_name='status')),
                ('product_vip', models.IntegerField(choices=[(0, 'Standart'), (1, 'VIP')], default=0, verbose_name='VIP status')),
                ('product_vip_moderation', models.IntegerField(choices=[(0, 'OK'), (1, 'Want VIP')], default=0, verbose_name='VIP moderation')),
                ('product_datatime_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='core.Category', verbose_name='category')),
            ],
        ),
    ]
