# Generated by Django 2.1.2 on 2018-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_wip',
        ),
        migrations.AddField(
            model_name='product',
            name='product_vip',
            field=models.IntegerField(choices=[(0, 'Standart'), (1, 'To moderation'), (2, 'VIP')], default=1, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_moderation',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'To moderation'), (2, 'Active')], default=1, verbose_name='Moderation'),
        ),
    ]
