# Generated by Django 2.1.2 on 2018-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181004_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_moderation',
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'To moderation'), (2, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_vip_moderation',
            field=models.BooleanField(choices=[(0, 'Standart'), (1, 'VIP')], default=0, verbose_name='VIP moderation'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vip',
            field=models.BooleanField(choices=[(0, 'Standart'), (1, 'VIP')], default=0, verbose_name='VIP status'),
        ),
    ]
