# Generated by Django 2.1.2 on 2018-10-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181006_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_vip_moderation',
            field=models.BooleanField(choices=[(0, 'OK'), (1, 'Want VIP')], default=0, verbose_name='VIP moderation'),
        ),
    ]
