# Generated by Django 2.1.2 on 2018-10-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181006_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'To moderation'), (2, 'Active')], default=1, max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vip',
            field=models.IntegerField(choices=[(0, 'Standart'), (1, 'VIP')], default=0, max_length=1, verbose_name='VIP status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vip_moderation',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'Want VIP')], default=0, max_length=1, verbose_name='VIP moderation'),
        ),
    ]
