# Generated by Django 2.1.2 on 2018-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181006_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_datatime_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
    ]
