# Generated by Django 2.1.2 on 2018-10-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_product_datatime_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_datatime_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
